[core]
arch = "x86_64"
machineId = "d9e4a2b7c1f850a396d24e1b87c5f3a6"
locale = "en_US.UTF-8"
timeZone = "Asia/Kolkata"
stateVersion = "26.05"
homeStateVersion = "26.05"
hostName = "spencer"
user = { name = "admin", description = "The spencer admin", hashedPassword = "$6$hPQHyhSk670MQJKC$qz1R/ygzNU.WlpZ78EIAepcIA/dusBtVMIf9VM4VDb5JLcJCL5jpsMBpOJhUTmOwhHXljZnIvnSNFtq5vIabk/" }

[services]

